apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: rh-selenium-hub
  namespace: selenium
  labels:
    app: rh-selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rh-selenium-hub
  template:
    metadata:
      labels:
        app: rh-selenium-hub
    spec:
      containers:
        - name: rh-selenium-hub
          image: selenium/hub:2.53.1
          ports:
            - containerPort: 4444
          resources:
            limits:
              memory: "1000Mi"
              cpu: ".5"
          livenessProbe:
            httpGet:
              path: /grid/console
              port: 4444
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /grid/console
              port: 4444
            initialDelaySeconds: 30
            timeoutSeconds: 5
          env:
            - name: GRID_TIMEOUT
              value: "100000"
            - name: GRID_BROWSER_TIMEOUT
              value: "100000"
